# Generated by Django 5.2.6 on 2025-09-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='va_beneficios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='va_habilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='va_responsabilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='va_tipo_empleo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
