# Generated by Django 5.2.6 on 2025-09-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_vacante_va_beneficios_vacante_va_habilidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='va_fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-18 07:17:00'),
            preserve_default=False,
        ),
    ]
