# Generated by Django 5.2.8 on 2025-11-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_vacante_va_fecha_publicacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="em_respuestas_a_tiempo",
            field=models.IntegerField(
                default=0, help_text="Postulaciones respondidas a tiempo"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="em_score_turbo",
            field=models.FloatField(
                default=5.0, help_text="Puntuación de confiabilidad (0-5)"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="em_total_postulaciones_turbo",
            field=models.IntegerField(
                default=0, help_text="Total de postulaciones turbo recibidas"
            ),
        ),
        migrations.AddField(
            model_name="postulacion",
            name="pos_es_turbo",
            field=models.BooleanField(
                default=False, help_text="Indica si es una postulación en modo turbo"
            ),
        ),
        migrations.AddField(
            model_name="postulacion",
            name="pos_fecha_limite_respuesta",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha límite para que la empresa responda",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="postulacion",
            name="pos_respondida_a_tiempo",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la empresa respondió dentro del plazo",
            ),
        ),
        migrations.AddField(
            model_name="vacante",
            name="va_modo_turbo",
            field=models.BooleanField(
                default=False, help_text="Activar modo de respuesta rápida"
            ),
        ),
        migrations.AddField(
            model_name="vacante",
            name="va_tiempo_respuesta_horas",
            field=models.IntegerField(
                default=48, help_text="Horas comprometidas para responder (24, 48 o 72)"
            ),
        ),
    ]
