# Generated by Django 5.2.8 on 2025-11-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_empresa_em_respuestas_a_tiempo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aspirante",
            name="asp_creditos_turbo_disponibles",
            field=models.IntegerField(
                default=3, help_text="Créditos turbo disponibles para usar"
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="asp_creditos_turbo_usados",
            field=models.IntegerField(
                default=0, help_text="Total de créditos turbo utilizados"
            ),
        ),
        migrations.AddField(
            model_name="postulacion",
            name="pos_creditos_turbo_usados",
            field=models.IntegerField(
                default=0,
                help_text="Créditos turbo utilizados en esta postulación (0 o 1)",
            ),
        ),
        migrations.AddField(
            model_name="postulacion",
            name="pos_turbo_solicitado_por_aspirante",
            field=models.BooleanField(
                default=False,
                help_text="El aspirante activó modo turbo en esta postulación",
            ),
        ),
    ]
