# Generated by Django 5.2.5 on 2025-12-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_aspirante_asp_creditos_turbo_disponibles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postulacion',
            options={'verbose_name': 'Postulación', 'verbose_name_plural': 'Postulaciones'},
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='asp_numeroId',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='em_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='em_nit',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último acceso'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('pos_aspirante_fk', 'pos_vacante_fk')},
        ),
    ]
