# Generated by Django 6.0 on 2025-12-15 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_postulacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Tipo de consentimiento (privacidad, marketing, cookies, etc)', max_length=50)),
                ('texto', models.TextField(help_text='Texto o versión del consentimiento otorgado')),
                ('otorgado_en', models.DateTimeField(auto_now_add=True)),
                ('aceptado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
