# Generated by Django 6.0 on 2025-12-16 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auditoriausuario'),
        ('usuarios', '0008_consentimiento'),
    ]

    operations = [
    ]
